[build]
  command = "npm install && cd client && npm install && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://quizmaster-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://quizmaster-app-kqm7.onrender.com/api"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://quizmaster-app-kqm7.onrender.com/api" 